# Generated by Django 5.1.15 on 2026-07-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='ai_personalization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
