# Generated by Django 5.1.15 on 2026-07-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='provider',
            field=models.CharField(default='mock', max_length=100),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='status',
            field=models.CharField(default='failed', max_length=50),
        ),
    ]
