# Generated by Django 5.1.15 on 2026-07-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_airequestlog_end_time_airequestlog_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrlog',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrlog',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrlog',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
