# Generated by Django 5.1.15 on 2026-07-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('blood_test', 'Blood Test'), ('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('doctor_consultation', 'Doctor Consultation Note'), ('vaccination', 'Vaccination Record'), ('medical_certificate', 'Medical Certificate'), ('radiology', 'Radiology Report'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
